"""add_farm_district_size_unit_irrigation_image

Revision ID: 1912cbe64abf
Revises: 0003_create_crops_table
Create Date: 2026-06-10 20:16:19.504199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912cbe64abf'
down_revision = '0003_create_crops_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('farms', sa.Column('district', sa.String(length=128), nullable=True))
    op.add_column('farms', sa.Column('size_unit', sa.String(length=32), nullable=True))
    op.execute("UPDATE farms SET size_unit = 'acres' WHERE size_unit IS NULL")
    op.alter_column('farms', 'size_unit', nullable=False)
    op.add_column('farms', sa.Column('irrigation_type', sa.String(length=128), nullable=True))
    op.add_column('farms', sa.Column('image_data', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'image_data')
    op.drop_column('farms', 'irrigation_type')
    op.drop_column('farms', 'size_unit')
    op.drop_column('farms', 'district')
    # ### end Alembic commands ###