"""add_farm_cultivated_crops

Revision ID: 387d70c71ee7
Revises: 1912cbe64abf
Create Date: 2026-06-10 20:39:20.863385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387d70c71ee7'
down_revision = '1912cbe64abf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('cultivated_crops', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'cultivated_crops')
    # ### end Alembic commands ###